development:
  sessions:
    default:
      database: member_api_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: member_api_test
      hosts:
        - localhost:27017

# <% if ENV['MONGOHQ_URL'] %>
# staging:
#   sessions:
#     default:
#       uri: <%= ENV['MONGOHQ_URL'] %>
#   options:
#     raise_not_found_error: false
# production:
#   sessions:
#     default:
#       uri: <%= ENV['MONGOHQ_URL'] %>
#   options:
#     raise_not_found_error: false
# <% end %>